CREATE DATABASE IF NOT EXISTS `bd2_ex10` COLLATE utf8_unicode_ci;
use bd2_ex10;

DROP TABLE IF EXISTS `houblon`;

CREATE TABLE `houblon` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(50) DEFAULT NULL,
  `pays` varchar(50) DEFAULT NULL,
  `utilisation` varchar(50) DEFAULT NULL,
  `alpha` varchar(50) DEFAULT NULL,
  `beta` varchar(50) DEFAULT NULL,
  `coh` varchar(50) DEFAULT NULL,
  `huile` varchar(50) DEFAULT NULL,
  `profil` varchar(255) DEFAULT NULL,
  `similitude` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO houblon (nom, pays, utilisation, alpha, beta, coh, huile, profil, similitude) VALUES 
('Admiral', 'Royaume-Uni', 'Amérisant', '13,5-16%', '5-6%', '37%-45%', '1-1,7ml pour 100g', 'Légèrement résineux et légèrement agrumes avec une pointe d''arômes herbeux', 'Target, Challenger'),
('Ahtanum', 'États-Unis', 'Aromatique', '5,7-6,3%', '5%-6,5%', '30%-35%', '0,8-1,2mL pour 100g', 'Profil agrumes et floral avec une pointe de pamplemousse un poil plus marquée sur le Cascade, Ce houblon peut Australiesi disposer de notes terreuses et résineuses', 'Cascade, Amarillo'),
('Amarillo', 'États-Unis', 'Double', '8-11%', '6-7%', '21-24%', '1,5-1,9mL pour 100g', 'Floral, agrumes, pamplemousse, fruits à noyaux', 'Cascade, Centennial, Citra'),
('Apollo', 'États-Unis', 'Amérisant', '18-22%', '5,5-8%', '24-28%', '1,5-2,5mL pour 100g', 'Orange et un poil résineux', 'Nugget, Columbus, Zeus, Magnum, Summit'),
('Aramis', 'France', 'Aromatique', '8%', 'Beta 4-4,5%', 'Co-H :', '1,2-1,6ml pour 100g', 'Herbeux, floral, terreux et citron', 'Strisselspalt, Willamette, Challenger, Hallertau, Tettnanger'),
('Aurora', 'Slovénie', 'Aromatique', '7-9%', '2,7%-5%', '22%-26%', '0,9-1,8ml pour 100g', 'Caractère houblonnée et légèrement fruité', 'Styrian Golding, Premiant, Northern Brewer'),
('Azacca', 'États-Unis', 'Double', '14-16%', '5,4%', '38%-45%', '1,6-2,5ml pour 100g', 'Zest d''agrumes, mandarine, mangue, pamplemousse, résine de pin, épicé et ananas,', null),
('Belma', 'États-Unis', 'Double', '12%', null, null, null,'Caractère houblonné fruité, fraise, melon, un peu agrumes', 'Pacific Gem'),
('Bramling Cross', 'Royaume-Uni', 'Aromatique', '7-10%', '2,3-3,2%', '33-35%', '0,7-1 mL pour 100g', 'Houblon anglais typique avec des arômes de mûres, de groseille et de citron', 'East Kent Goldings, Progress, Brewer''s Gold'),
('Bravo', 'États-Unis', 'Amérisant', '14-17%', '3,5-5,5%', '28-35%', '2,3-3,5 mL pour 100g', 'Souple, équilibré, fruité (orange) et floral', 'Warrior'),
('Brewer''s Gold', 'États-Unis', 'Amérisant', '4-11%', '4-6,5%', '40-48%', '1,5-3 mL pour 100g', 'Un houblon spécifique pour amérisant avec des notes épicés et de mûres', 'Bullion, Galena, Bramling Cross'),
('Bullion', 'États-Unis', 'amérisant', '7-9%', '4,1-4,6%', '38-40%', '1-2 mL pour 100g', 'Précédement, un houblon amérisant pour les stouts, Résineux, terreux et arôme intese de framboises et mûres,', 'Brewer''s Gold, Galena'),
('Calypso', 'États-Unis', 'Double', '12-14%', '5-6%', '40-42%', '1,5 à 2,5ml pour 100g', 'Arôme citronnée, de pommes et de thé vert', 'aucun'),
('Cascade', 'États-Unis', 'Aromatique', '7,7-9,1%', '6,4-7,1%', '33-40%', '0,8-2,5 mL pour 100g', 'Légèrement floral avec des notes très agrumes (pamplemousse)', 'Centennial'),
('Cashmere', 'États-Unis', 'Double', '4,5-7,0%', '4,8-7%', '22-24%', '1,2-1,4 mL pour 100g', 'Modéremment herbeux avec des notes de melon, de citron vert et finement épicé', 'Cascade'),
('Centennial', 'États-Unis', 'Double', '9-12%', '3,5-4,5%', '28-30%', '1-3mL pour 100g', 'Balancé, fruité, agrumes avec des notes de fruits à noyaux', 'Cascade, Citra'),
('Challenger', 'Royaume-Uni', 'Double', '6-9 %', '4-4,5%', '20-25%', '1-1,7mL pour 100g', 'Un houblon avec un arôme spécifique de cèdre, de thé vert et de fruit sucré ', 'Perle, Target, Phoenix, EKG'),
('Chinook', 'États-Unis', 'Double', '11-14%', '3-4%', '29-34%', '1-2,5mL pour 100g', 'Épicié, avec des notes de pins et d''agrumes', 'Nugget, Columbus, Northern Brewer'),
('Citra', 'États-Unis', 'Double', '10-12%', '3,5-4,5%', '22-24%', '1,5-3mL pour 100g', 'Arôme intense de mangue, fruit tropicaux et agrumes, Note de melon, citron vert, groseille ou litchi, Idéal dry hop ou en aromatique, ', 'Galaxy, Centennial, Nelson Sauvin'),
('Cluster', 'États-Unis', 'Double', '5,5-8,5%', '4-6%', '36-41%', '0,5-1mL pour 100g', 'Floral, terreux et fruits sucrés,', 'Galena, Northern Brewer'),
('Columbus / Tomahawk / Zeus (CTZ)', 'États-Unis', 'Double', '14-16%', '4,5-5,5%', '30-35%', null, 'Dank, terreux, résineux, poivre, réglisse, curry et un poil d''agrumes,', 'Chinook, Nugget'),
('Comet', 'États-Unis', 'Amérisant', '9-11%', '4-5%', '34-37%', '1,2-2mL pour 100g', 'Intense caractère d''agrumes et extrêmement « dank »', 'Summit'),
('Crystal', 'États-Unis', 'Aromatique', '2-5%', '6-8,5%', '23-26%', '0,8-2,3mL pour 100g', 'Un hybride US du Hallertau, très floral, arômes épicés,', 'Mont Hood, Hersbrucker, Liberty, Hallertau'),
('Dana', 'Slovénie', 'Double', '11-16%', '4,8-6%', '28-31%', '2,4-3,9mL pour 100g', 'Une pseudo houblon noble avec un caractère rustique, un côté épicé et une amertume modérée,', 'aucun'),
('Delta', 'États-Unis', 'Double', '5,5-7%', '5,5-7%', '22-24%', '0,5-1,1mL pour 100g', 'Légèrement épciié avec des notes d''agrumes, Un croisement entre Fuggles et Cascade, ', 'Cascade, Fuggle, Willamette'),
('East Kent Goldings', 'Royaume-Uni', 'Aromatique', '4,5-6,5%', '1,9-2,8%', '28-32%', '0,4-0,8mL pour 100g', 'Un houblon traditionnel anglais populaire pour ses fragances raffinées, ses notes délicates épicées et florales, Lavende, épices, miel, thym, pamplemousse,', 'Fuggle, First Gold, Williamette'),
('El Dorado', 'États-Unis', 'Double', '14-16%', '7%-8%', '28%-33%', '2,50-3,3mL pour 100g', 'Des puissants arômes de bonbons cerise, de poire ou de fruit sucré,', 'aucun'),
('Equinox / Ekuanot', 'États-Unis', 'Aromatique', '14,4-15,6%', '4,6-5,1%', '31,7-38%', '2,5-4,5mL pour 100g', 'Citron jaune, citron vert, papaye, pomme verte, florale et herbeux', 'aucun'),
('Falconers Flight', 'États-Unis', 'Double', '10,5%', '4%-5%', '20%-25%', '1,6-4,6mL pour 100g', 'Agrumes, tropical, floral, citron et pamplemousse,', 'Cascade, Ahtanum, Sorachi Ace'),
('First Gold', 'Royaume-Uni', 'Double', '6-9%', '2,3-4,1%', '32-34%', '0,7-1,5mL pour 100g', 'Un hybride du Golding, plutôt similaire : épicé, boisé, mentholé', 'Eat Kent Goldings, Fuggle, Crystal'),
('Fuggle', 'Royaume-Uni', 'Aromatique', '4-6%', '2-3%', '25-30%', '0,7-1,4mL pour 100g', 'Boisé, terreux, modérément épicié', 'Williamette, Styrian Goldings'),
('Galaxy', 'Australie', 'Double', '13-15%', '5,8-6%', '35% ', '3-5mL pour 100g', 'Fruit de la passion, fruit tropicaux, agrumes et notes de pêches et de mangues,', 'Citra, Amarillo'),
('Galena', 'Royaume-Uni', 'Amérisant', '11-14%', '7,5-8,5%', '34-39%', '1,3-2,1mL pour 100g', 'Fruité, mûres et agrumes', 'Legacy, Brewer''s Gold, Nugget'),
('Glacier', 'États-Unis', 'Double', '5-6%', '7-10%', '13-16%', '0,8-1mL pour 100g', 'Terreux, floral avec des notes sucrées d''agrumes, de prunes et de mûres,', 'Williamette, Styrian Goldings'),
('Green Bullet', 'Nouvelle-Zélande', 'Double', '10-14%', '6,5-7%', '38-39%', '1-1,2mL pour 100g', 'Fruité, résineux, connu pour ses arômes distinctifs de raisin sec,', 'Galena'),
('Hallertau', 'Allemagne', 'Aromatique', '3,5-5,5%', '3-4%', '17-24%', null, 'Vertsatile, houblon modéremment épicié, floral, un peu terreux, Houblon "noble"', 'Hersbruck, Mont Hood, Liberty, Helga'),
('Hallertau Aroma ou Wakatu', 'Nouvelle-Zélande', 'Aromatique', '7-9%', '5,8-8,5%', '28-35%', '0,9-1,1mL pour 100g', 'Arômes spécifique de zest frais de citron vert, épicié et floral,', 'aucun'),
('Hallertau Blanc', 'Allemagne', 'Aromatique', '9-12%', '4,5-5,5%', '22-26%', '1,2-1,5mL pour 100g', 'Floral et fruité avec des arômes de fruits de la passion, de pamplemousse de groseille et d''ananas', 'Le Galaxy / Nelson Sauvin allemand'),
('Hallertau Mittelfrüh', 'Allemagne', 'Aromatique', '3,5%', '3,5-4,5%', '20-26%', '0,7-1,3mL pour 100g', 'Versatile, épicé et floral avec des notes terreuse, Houblon Noble,', 'Hersbruck, Mont Hood, Liberty, Helga'),
('Helga', 'Australie', 'Aromatique', '5-6,3%', '5-7%', '20-23%', '0,6-1mL pour 100g', 'Un houblon dans le style "noble" plutôt floral', 'Hallertau Mittelfrueh, Hersbrucker'),
('Herald', 'Royaume-Uni', 'Double', '9-13%', '4,8%-5,5%', '35%-37%', '1-1,9mL pour 100g', 'Un cousin du Pionnier, grosse amertume et caractère d''agrumes,', 'Pioneer'),
('Herkules', 'Allemagne', 'Amérisant', '12-17%', '4-5,5%', '32-38%', '1,6-2,4mL pour 100g', 'Légèrement fruité (melon et agrumes)', 'Horizon, Magnum, Hallertau Taurus'),
('Hallertau Hersbrucker', 'Allemagne', 'Aromatique', '2-5%', '4-6%', '19-25%', '0,5-1mL pour 100g', 'Modérément floral avec des notes de tabacs et de foin,', 'Hallertau, Helga'),
('Horizon', 'États-Unis', 'Double', '10-16%', '5,5-7,5%', '16-19%', '0,5-1,5mL pour 100g', 'Agrumes et fleurs, très parfumé avec un peu de résineux,', 'Magnum, Amarillo'),
('Hüll Melon', 'Allemagne', 'Aromatique', '6,9-7,5%', '7,3-7,9%', '25-30%', '0,7-0,9mL pour 100g', 'Fraise et melon jaune', 'aucun'),
('Kohatu', 'Nouvelle-Zélande', null, '6-7%', '5,8-3,5%', '21%', '1-1mL pour 100g', 'Très floral et pamplemousse, aiguilles de pins et fruits tropicaux,', 'aucun'),
('Liberty', 'États-Unis', 'Aromatique', '3-6%', '3-4%', '22-24%', '1-1,8mL pour 100g', 'Epicé, résineux, il est parfois considéré comme un houblon noble,', 'Hallertau'),
('Marynka', 'Pologne', 'Double', '7-10%', '10,2%-13%', '26%-33%', '1,8-2,2mL pour 100g', 'Terreux, racineux, réglisse', 'Perle, Chinook'),
('Magnum', 'Allemagne', 'Amérisant', '11-15%', '5,5-8%', '23-28%', '2-3mL pour 100g', 'Amertume très propre, modérée et subtile,', 'Horizon'),
('Mandarina Bavaria', 'Allemagne', 'Aromatique', '7-10%', '5-6,5%', '31-35%', '2,1-2,3mL pour 100g', 'Mandarine, mandarine, Agrumes', 'aucun'),
('Merkur', 'Allemagne', 'Double', '12-15%', '4,5-5,5%', '18-20%', '2-3mL pour 100g', 'Similaire au Magnum mais plus terreux et floral, Arôme spécifique de menthe, sucre et ananas,', 'Magnum, Horizon'),
('Millennium', 'États-Unis', 'Amérisant', '13-16%', '4,8%', '30%', '1,5-3mL pour 100g', 'Amertume propre et arôme herbeux, résinueux, toffee et poire,', 'Nugget'),
('Mosaic', 'États-Unis',null,  '10-12%', '3,2-3,9%', '24-26%', '0,8-3mL pour 100g', 'Mangue, papaye, rose, fruits à noyaux, 4 baies, melon, chewing gum, herbeux parfois, ', 'Galaxy, Nelson Sauvin'),
('Motueka', 'Nouvelle-Zélande', 'Aromatique', '6,5 -7,5%', '5-5,5%', '28-30%', '0,7-0,9mL pour 100g', 'Citron, fruits tropicaux, épices, zest de citron vert frais (mojito) ', 'Saaz'),
('Mount Hood', 'États-Unis', 'Aromatique', '5-8%', '4,4-7,2%', '21-25%', '0,8-2mL pour 100g', 'Herbeux, épicé et légèrement mazooté ', 'Hallertauer, Tettnanger'),
('Mount Rainier', 'États-Unis', 'Double', '5-8%', '8-10%', '21-23%', '1,5-2,5mL pour 100g', 'Arome d''agrumes, de fleur et de réglisse', 'Hallertauer, Fuggles'),
('Nelson Sauvin', 'Nouvelle-Zélande', 'Double', '11-13%', '6-8%', '22-26%', '1,1-1,1mL pour 100g', 'Vin blanc, pamplemousse, baie acidulée, dank et intensément fruité, groseille écrasée, ', 'aucun'),
('Newport', 'États-Unis', 'Amérisant', '12-15%', '5,5-6,5%', '36-38%', '1,6-2,5mL pour 100g', 'Agrumes, terreux, vin et balsamic', 'Magnum'),
('Northdown', 'Royaume-Uni', 'Double', '6-10%', 'Alpha: 7,5-9,5%', '5-5,5%', '24-30%', 'Amertume propre avec des notes boisées et mentholées,', 'Northern Brewer'),
('Northern Brewer', 'Royaume-Uni', 'Double', '8-10%', '3,5-5,5%', '30-34%', '1-2mL pour 100g', 'Boisé, mentholée et pinède', 'Northdown, Perle, Aurora'),
('Nugget', 'États-Unis', 'Amérisant', '10-14%', '4,4-5,5%', '22-26%', '1-3mL pour 100g', 'Amertume herbeuse', 'Galena, Columbus'),
('Opal', 'Allemagne', 'Double', '8-10%', '3,5-5,5%', '13-17%', '0,8-1,3mL pour 100g', 'Amertume modérée, épicé, poivré, fruité et floral, Moderate bitterness, spicy, fruity, floral, ', 'Saphir, East Kent Goldings'),
('Pacific Gem', 'Nouvelle-Zélande', 'Amérisant', '13-16%', '7-9%', '36-38%', '1,1-1,3mL pour 100g', 'Amertume propre, arômes légers de fraises, mûres, mélanges de baies, agrumes acidulées, melon', 'Belma'),
('Pacifica', 'Nouvelle-Zélande', 'Aromatique', '5 -6%', '5,9-6,1%', '24-26%', '0,9-1,1mL pour 100g', 'Marmelade d''orange, agrumes et floral,', 'Mittlefruh et Amarillo'),
('Pacific Jade', 'Nouvelle-Zélande', 'Aromatique', '12-14%', '7-8%', '23-25%', '1,4-1,4mL pour 100g', 'Amertume légère, arôme prononcé d''agrumes et de poivre moûlu', 'Magnum'),
('Palisade', 'États-Unis', 'Double', '5,5-9,5%', '5,5-8%', '26-28%', '0,8-2mL pour 100g', 'Fruité et sans agrumes, terreux et minéral,', 'Willamette'),
('Perle', 'Allemagne', 'Aromatique', '6-8%', '2,5-4,5%', '29-35%', '0,5-1,5mL pour 100g', 'Épicé, mentholé et floral,', 'Northern Brewer, Northdown'),
('Phoenix', 'Royaume-Uni', 'Double', '7-11%', '3,8-4,5%', '0%', '1,2-2,5mL pour 100g', 'Épicé, floral et chocolaté,', 'Challenger Northern Brewer'),
('Pilgrim', 'Royaume-Uni', 'Double', '9-13%', '4,3-5%', '36-38%', '1,2-2,4mL pour 100g', 'Épicé, citron, pamplemousse, poire et baies,', 'Target'),
('Pioneer', 'Royaume-Uni', 'Double', '8-10%', '3,2-4,9%', '33-40%', '1,5-2,3mL pour 100g', 'Agrumes (citron, pamplemousse) avec des notes herbeuses de cèdres', 'EKG'),
('Polaris', 'Allemagne', 'Double', '19-23%', '4,5-6%', '22-28%', '4-5mL pour 100g', 'Mentholée, ananas, bonbon menthe', 'aucun'),
('Premiant', 'République-Tchèque', 'Amérisant', '7-10%', '3,5-5,5%', '18-23%', '1-2mL pour 100g', 'Arôme modérée', 'Styrian Goldings, Saaz, Aurora'),
('Pride of Ringwood', 'Australie', null, '9-10,5%', '5,5-6%', '32%', '1,6-1,8mL pour 100g', 'Unique, arôme intense boisé, liège, agrumes et herbeux,', 'Cluster, Galena'),
('Progress', 'Royaume-Uni', 'Double', '5-7%', '2-2,7%', '25-30%', '0,5-0,8mL pour 100g', 'Modérément épicé et boisé, notes de genièvrier,', 'Fuggle'),
('Rakau', 'Nouvelle-Zélande', 'Double', '9-11%', '4,6%', '25%', '2,2-2,2mL pour 100g', 'Herbe fraîche, épicié en attaque, avec des notes de pèches aciduées et de figues à la fin, Pointes d''abricots et d''aiguilles de pins,', 'aucun'),
('Riwaka', 'Nouvelle-Zélande', 'Aromatique', '5-7%', '4-5%', '31-33%', '1,4-1,6mL pour 100g', 'Très fort en agrumes et en pamplemousse avec des notes de fruits tropicaux,', 'Cascade'),
('Saaz', 'République-Tchèque', 'Aromatique', '3-5%', '4-6%', '23-26%', '0,4-0,8mL pour 100g', 'Le houblon noble typique qui exprime le mieux les arômes épicés typique des pilsners tchèques, Un poil terreux, herbal et minéral,', 'Sterling, Spalt'),
('Santiam', 'États-Unis', 'Aromatique', '5-7%', '7-8%', '22-24%', '1-2,2mL pour 100g', 'Herbal et floral, ', 'Tettnang'),
('Saphir', 'Allemagne', 'Aromatique', '3-5,5%', '4-7%', '12-17%', '0,8-1,4mL pour 100g', 'Sucré, propre et épicé, Agrumes voire même mandarine,', 'Hallertau'),
('Satus', 'États-Unis', 'Amérisant', '12,5-14,0%', '8,5%-9%', '32%-35%', null, 'Fruits sucrés, poires, ananas, mûres, citrons verts, groseille,', 'Galena'),
('Select', 'Allemagne', 'Aromatique', '4-6%', '2,4-5%', '21-27%', '0,6-0,9mL pour 100g', 'Pelouse et épicé', 'Spalt, Tettnang, Saaz'),
('Serebrianka', 'Russie', 'Aromatique', '3,5%', '3%', '23%', '0,41mL pour 100g', 'Houblon très léger', 'aucun'),
('Simcoe', 'États-Unis ', 'Double', '11-14%', '4-5%', '15-20%', '0,8-3,2mL pour 100g', 'Pinède, agrumes, baies sucrée et parfumées,', 'A combination of Columbus and Centennial might come close,'),
('Smaragd', 'Allemagne', 'Double', '4-6%', '3,5-5,5%', '13-18%', '0,4-0,8mL pour 100g', 'Note fruité et floral,', 'aucun'),
('Sorachi Ace', 'Japon', 'Double', '12-16%', '6-7,5%', '25-28%', '1,5-3mL pour 100g', 'Citronée, citronelle, sorbet au citron vert,', 'Southern Cross'),
('Southern Cross', 'Nouvelle-Zélande', 'Double', '11-14%', '5-6%', '25-28%', '1,2-1,2mL pour 100g', 'Citron, citron vert, pinède,', 'Sorachi Ace'),
('Sovereign', 'Royaume-Uni', 'Double', '4-7%', '2,1-3,1%', '26-30%', '0,6-1mL pour 100g', 'Terreux, fruits secs (noix) et pinède,', 'Fuggle'),
('Spalt', 'Allemagne', 'Aromatique', '3,5-5%', '3-5%', '22-29%', '0,5-0,9mL pour 100g', 'Épicé', 'Saaz, Tettnang'),
('Stella', 'Australie', 'Double', '14-16%', '4-4,5%', '36%', null, 'Épicé, terreux, notes d''étoiles d''anis et floral,', 'Mix of English and Noble varieties'),
('Sterling', 'États-Unis', 'Aromatique', '5-9%', '4,5-6%', '22-27%', '1-2mL pour 100g', 'Floral, épicé, légèrement agrumes,', 'Saaz'),
('Sticklebract', 'Nouvelle-Zélande', 'Double', '11-14%', '7,5%-8,5%', '40%-45%', '0,76-1,72mL pour 100g', 'Pinède, agrumes', 'Northern Brewer'),
('Strisselspalt', 'France', 'Aromatique', '3-5%', '4-4,7%', '20-23%', '0,6-0,8mL pour 100g', 'Épicé, agrumes, floral, fruité et herbeux,', 'Hersbrucker, Hallertau'),
('Styrian Goldings', 'Slovénie', 'Double', '4,5-6%', '3,5%-5,9%', '28%-35%', null, 'Épicé', 'Aurora, Fuggle, Williamette'),
('Summer', 'Australie', 'Aromatique', '4-7%', '4,8-6,1%', '23-25%', '1,4-2mL pour 100g', 'Abricot, marmelade orange, groseilles, épicé, ', 'Rakau, Amarillo'),
('Summit', 'États-Unis', 'Amérisant', '17-19%', '5-6,5%', '29-32%', '1,5-3mL pour 100g', 'Amertume souple orangée, mandarine, caractère d''agrumes,', 'Apollo'),
('Super Pride', 'Australie', 'Amérisant', '9-10,5%', '5,5-6%', '32%', '3,4-4mL pour 100g', 'Unique, arôme de liège, agrumes, herbeux,', 'Cluster, Galena'),
('Tahoma', 'États-Unis', null, '7,2-8,2%', '8,5-9,5%', '15-17%', null, 'Citrus and lemon notes, cedar, pine, floral, subtle melon,', 'aucun'),
('Target', 'Royaume-Uni', 'Aromatique', '8-13%', '7-8%', '15-17%', '1,5-2mL pour 100g', 'Herbal, terreux, herbe fraîche', 'Admiral'),
('Hallertau Taurus', 'Allemagne', 'Double', '12-17%', '4%-6%', '23%-25%', '0,9-1,5mL pour 100g', 'Noble, aromatique, zest d''agrumes', 'Horizon, Herkules, Magnum'),
('Tettnang', 'Allemagne', 'Aromatique', '3,5-5%', '2,8%-5,3%', '24%', '0,36-1,07mL pour 100g', 'Herbal, légèrement épicié et boisé', 'Saaz, Spalt, Ultra'),
('Topaz', 'Australie', 'Double', '15,5-18%', '6-7%', '47-50%', '1,7-2,2mL pour 100g', 'Litchi, mandarine, épicé et raisin sec,', 'Rakau, Stella'),
('Tradition', 'Allemagne', 'Aromatique', '5-7%', '3-6%', '24-30%', '0,5-1mL pour 100g', 'Fleur sucrée, terreux,', 'Hallertau, Liberty'),
('Triplepearl', 'États-Unis', 'Aromatique', '10,2-11,2%', '3,3-4,2%', '21-25%', '1,1-1,8mL pour 100g', 'Notes de melons, orange, raisins secs, épicés et poivre,', 'Pearl'),
('Triskel', 'France', 'Aromatique', '8-9%', '4-4,7%', '20-23%', '1,5-2mL pour 100g', 'Très floral, agrumes et épices', 'Strisselspalt, Ahtanum'),
('Ultra', 'États-Unis', 'Aromatique', '9,2-9,7%', '3,8-4%', '23-38%', '1-1,5mL pour 100g ', 'Épicé, floral, bon houblon de remplacement des houblons nobles,', 'Saaz, Spalt, Tettnang'),
('Vanguard', 'États-Unis', 'Aromatique', '5-6%', '5,5-7%', '18-20%', '0,5-1mL pour 100g', 'Légèrement floral, herbeux,', 'Hallertau, Spalt, Tettnang'),
('Vic Secret', 'Australie', 'Double', 'Alpha: 14-17%', '6,1-7.8%', '51-56%', '2,2-2,8mL pour 100g', 'Ananas, fruits tropicaux, fruits à noyaux, agrumes, pamplemousse, pin, résineux, dank', 'Galaxy'),
('Wai-ti', 'Nouvelle-Zélande', 'Aromatique', 'Alpha: 2,5-3,5%', '4,5-5,5%', '22-24%', '1,6-1,6mL pour 100g', 'Pèche, abricot, et citron vert fraîchement zesté, épicé,', 'Riwaka'),
('Waimea', 'Nouvelle-Zélande', 'Double', '15-16%', '7-9%', '22-24%', '2-2,2mL pour 100g', 'Aiguilles de pins, agrumes, pamplemouses et mandarine,', 'aucun'),
('Wakatu', 'Nouvelle-Zélande', 'Double', '7-9%', '5,8%-8,5%', '28-35%', '0,9-1,1mL pour 100g', 'Légèrement épicié, floral et agrumes (citron vert),', 'aucun'),
('Warrior', 'États-Unis', 'Amérisant', '15-17%', '4,4-6%', '25-28%', '1-2,5mL pour 100g', 'Arôme moelleux d''agrumes, citron', 'Bravo, Apoll, Magnum'),
('Willamette', 'États-Unis', 'Aromatique', '4-6%', '3,5-4,5%', '30-35%', '0,6-1,6mL pour 100g', 'Herbeux, boisé, terreux et notes de sureau', 'Fuggle, Tettnang'),
('Yakima Gold', 'États-Unis', 'Double', '8,8-10,5%', '4,3-5,0%', '21-23%', '1,9-2,3mL pour 100g', '', 'Pearl'),
('Zythos', 'États-Unis', 'Aromatique', '10-12%', '4,7-6,2%', '28-31%', '0,7-1,2mL pour 100g', 'Très aromatique, mandarine, citron, pamplemousse, notes de pin', 'Cascade, Ahtanum, Sorachi Ace');






